// file: ram.v

`timescale 1ns/1ns

module ram(clk,we,adr,din,dout);

parameter depth =256;
parameter bits = 32;
parameter width = 32;

input clk, we;
input [bits-1:0] adr;
input [width-1:0] din;

output [width-1:0] dout;

reg [width-1:0] Dmem [depth-1:0];
integer i;

initial begin
	for (i = 0; i < depth; i = i + 1)
		Dmem[i] = 32'b0;

	// Load 10-word .data segment generated by the assembler
	$readmemb("generated/inputs/mean_max_min.out.no_address.data.bin", Dmem, 0, 9);
end
    
assign dout = Dmem[adr];
    
always @ (posedge clk) begin
	
    if (we) 
		Dmem[adr] <= din;
		 
end

endmodule